spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: identity_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG